#!/bin/sh
rm 'RTLS Documentation.aux'
rm 'RTLS Documentation.fdb_latexmk'
rm 'RTLS Documentation.fls'
rm 'RTLS Documentation.lof'
rm 'RTLS Documentation.log'
rm 'RTLS Documentation.lot'
rm 'RTLS Documentation.synctex.gz'
rm 'RTLS Documentation.toc'
rm 'RTLS Documentation.pdf'
